package com.nicolaielgame.game.model

import androidx.compose.ui.graphics.Color

enum class EnemyType(
    val title: String,
    val maxHealth: Float,
    val speed: Float,
    val reward: Int,
    val scoreValue: Int,
    val sizeScale: Float = 1f,
    val isBoss: Boolean = false,
    val regenPerSecond: Float = 0f,
    val slowVulnerability: Float = 1f,
    val damageTakenMultiplier: Float = 1f,
    val primaryColor: Color,
    val accentColor: Color,
) {
    Normal(
        title = "Normal",
        maxHealth = 40f,
        speed = 0.92f,
        reward = 11,
        scoreValue = 18,
        primaryColor = Color(0xFFC6284E),
        accentColor = Color(0xFFFF8A72),
    ),
    Fast(
        title = "Fast",
        maxHealth = 30f,
        speed = 1.34f,
        reward = 9,
        scoreValue = 16,
        primaryColor = Color(0xFFD26A1E),
        accentColor = Color(0xFFFFD166),
    ),
    Tank(
        title = "Tank",
        maxHealth = 122f,
        speed = 0.6f,
        reward = 22,
        scoreValue = 38,
        primaryColor = Color(0xFF5E4A8A),
        accentColor = Color(0xFFBCA7FF),
    ),
    Shielded(
        title = "Shielded",
        maxHealth = 92f,
        speed = 0.72f,
        reward = 24,
        scoreValue = 46,
        damageTakenMultiplier = 0.58f,
        primaryColor = Color(0xFF195D78),
        accentColor = Color(0xFFFFF275),
    ),
    Swarm(
        title = "Swarm",
        maxHealth = 18f,
        speed = 1.55f,
        reward = 6,
        scoreValue = 12,
        sizeScale = 0.72f,
        slowVulnerability = 1.08f,
        primaryColor = Color(0xFFB21F73),
        accentColor = Color(0xFFFF9AD5),
    ),
    Boss(
        title = "Boss",
        maxHealth = 540f,
        speed = 0.45f,
        reward = 90,
        scoreValue = 190,
        sizeScale = 1.75f,
        isBoss = true,
        primaryColor = Color(0xFF732447),
        accentColor = Color(0xFFFFD166),
    ),
    Juggernaut(
        title = "Juggernaut",
        maxHealth = 700f,
        speed = 0.4f,
        reward = 120,
        scoreValue = 255,
        sizeScale = 1.95f,
        isBoss = true,
        slowVulnerability = 0.45f,
        primaryColor = Color(0xFF4D365F),
        accentColor = Color(0xFFFFC857),
    ),
    Regenerator(
        title = "Regenerator",
        maxHealth = 610f,
        speed = 0.48f,
        reward = 130,
        scoreValue = 275,
        sizeScale = 1.82f,
        isBoss = true,
        regenPerSecond = 6.5f,
        slowVulnerability = 0.72f,
        primaryColor = Color(0xFF1D674D),
        accentColor = Color(0xFF7CFF6B),
    ),
}

