package com.nicolaielgame.game.model

import androidx.compose.ui.graphics.Color

enum class EnemyType(
    val title: String,
    val maxHealth: Float,
    val speed: Float,
    val reward: Int,
    val scoreValue: Int,
    val sizeScale: Float = 1f,
    val isBoss: Boolean = false,
    val regenPerSecond: Float = 0f,
    val slowVulnerability: Float = 1f,
    val primaryColor: Color,
    val accentColor: Color,
) {
    Normal(
        title = "Normal",
        maxHealth = 42f,
        speed = 0.95f,
        reward = 10,
        scoreValue = 18,
        primaryColor = Color(0xFFC6284E),
        accentColor = Color(0xFFFF8A72),
    ),
    Fast(
        title = "Fast",
        maxHealth = 28f,
        speed = 1.38f,
        reward = 8,
        scoreValue = 16,
        primaryColor = Color(0xFFD26A1E),
        accentColor = Color(0xFFFFD166),
    ),
    Tank(
        title = "Tank",
        maxHealth = 130f,
        speed = 0.62f,
        reward = 20,
        scoreValue = 38,
        primaryColor = Color(0xFF5E4A8A),
        accentColor = Color(0xFFBCA7FF),
    ),
    Boss(
        title = "Boss",
        maxHealth = 560f,
        speed = 0.46f,
        reward = 80,
        scoreValue = 180,
        sizeScale = 1.75f,
        isBoss = true,
        primaryColor = Color(0xFF732447),
        accentColor = Color(0xFFFFD166),
    ),
    Juggernaut(
        title = "Juggernaut",
        maxHealth = 720f,
        speed = 0.42f,
        reward = 105,
        scoreValue = 240,
        sizeScale = 1.95f,
        isBoss = true,
        slowVulnerability = 0.45f,
        primaryColor = Color(0xFF4D365F),
        accentColor = Color(0xFFFFC857),
    ),
    Regenerator(
        title = "Regenerator",
        maxHealth = 620f,
        speed = 0.5f,
        reward = 115,
        scoreValue = 260,
        sizeScale = 1.82f,
        isBoss = true,
        regenPerSecond = 8f,
        slowVulnerability = 0.72f,
        primaryColor = Color(0xFF1D674D),
        accentColor = Color(0xFF7CFF6B),
    ),
}

